// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Manual sidebar for Physical AI Courseware
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module2-simulation',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module3-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module4-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone',
        },
      ],
    },
  ],
};

export default sidebars;
